# Dev sites
e9tests:             &dev
  site_id:           5
  rainmaker:         devsecure.eloquacorp.com
  root_domain:       dev.eloquacorp.com # Rainmaker rootdomain
  first_party_domain: trackinglp01.com

e10tests:
  <<:                *dev
  site_id:           3
  first_party_domain: trackinglp01.com

# QA01P03 sites
tramane9qa01pod03:   &qa01p03
  site_id:           1862342680
  rainmaker:         secure.p03.elqqa01.com
  root_domain:       elqqa01.com

tramane10qa01p03:
  <<:                *qa01p03
  site_id:           952160201

