dev:
  rainmaker:             devsecure.eloquacorp.com
  root_domain:           dev.eloquacorp.com # Rainmaker rootdomain
  sites:
    e10tests:            3
    e9tests:             5

qa01p03:
  rainmaker:             secure.p03.elqqa01.com
  root_domain:           elqqa01.com
  sites:
    tramane9qa01pod03:   1862342680
    tramane10qa01pod03:  952160201

